(define (problem problem_292)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj8)
	(connected obj0 obj10)
	(connected obj1 obj0)
	(connected obj1 obj8)
	(connected obj1 obj9)
	(connected obj2 obj0)
	(connected obj3 obj0)
	(connected obj3 obj4)
	(connected obj3 obj7)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj9)
	(connected obj5 obj0)
	(connected obj5 obj8)
	(connected obj6 obj3)
	(connected obj6 obj7)
	(connected obj6 obj9)
	(connected obj7 obj1)
	(connected obj7 obj6)
	(connected obj7 obj8)
	(connected obj8 obj0)
	(connected obj8 obj1)
	(connected obj8 obj5)
	(connected obj8 obj7)
	(connected obj9 obj1)
	(connected obj9 obj4)
	(connected obj9 obj6)
	(connected obj10 obj0)
	(connected obj10 obj4)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)