(define (problem problem_213)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj6)
	(connected obj0 obj10)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj6)
	(connected obj1 obj8)
	(connected obj2 obj0)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj8)
	(connected obj3 obj1)
	(connected obj3 obj7)
	(connected obj4 obj5)
	(connected obj4 obj10)
	(connected obj5 obj2)
	(connected obj5 obj4)
	(connected obj5 obj8)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj7 obj2)
	(connected obj7 obj3)
	(connected obj7 obj9)
	(connected obj8 obj1)
	(connected obj8 obj2)
	(connected obj8 obj5)
	(connected obj9 obj7)
	(connected obj9 obj10)
	(connected obj10 obj0)
	(connected obj10 obj2)
	(connected obj10 obj4)
	(connected obj11 obj5)
	(connected obj12 obj2)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)