(define (problem problem_1446)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj11)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj1 obj6)
	(connected obj1 obj10)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj10)
	(connected obj2 obj12)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj6)
	(connected obj3 obj7)
	(connected obj3 obj8)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj3)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj3)
	(connected obj5 obj9)
	(connected obj5 obj11)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj3)
	(connected obj7 obj0)
	(connected obj7 obj3)
	(connected obj7 obj8)
	(connected obj7 obj9)
	(connected obj8 obj3)
	(connected obj8 obj7)
	(connected obj9 obj5)
	(connected obj9 obj7)
	(connected obj10 obj1)
	(connected obj10 obj2)
	(connected obj11 obj5)
	(connected obj11 obj12)
	(connected obj12 obj2)
	(connected obj12 obj11)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj8)
	(visited obj10)
	(visited obj11)
	(visited obj12)
))
)