(define (problem problem_1594)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj6)
	(connected obj1 obj8)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj13)
	(connected obj3 obj0)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj9)
	(connected obj3 obj10)
	(connected obj4 obj0)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj7)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj5 obj7)
	(connected obj5 obj10)
	(connected obj5 obj11)
	(connected obj6 obj1)
	(connected obj6 obj5)
	(connected obj6 obj8)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj7 obj5)
	(connected obj7 obj9)
	(connected obj7 obj12)
	(connected obj8 obj0)
	(connected obj8 obj1)
	(connected obj8 obj6)
	(connected obj8 obj10)
	(connected obj9 obj3)
	(connected obj10 obj3)
	(connected obj10 obj5)
	(connected obj10 obj8)
	(connected obj11 obj5)
	(connected obj12 obj7)
	(connected obj13 obj2)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj10)
))
)