(define (problem problem_357)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj4)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj13)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj9)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj6)
	(connected obj4 obj7)
	(connected obj4 obj8)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj5 obj11)
	(connected obj5 obj14)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj3)
	(connected obj6 obj4)
	(connected obj6 obj5)
	(connected obj6 obj7)
	(connected obj6 obj8)
	(connected obj7 obj0)
	(connected obj7 obj6)
	(connected obj8 obj2)
	(connected obj8 obj4)
	(connected obj8 obj6)
	(connected obj9 obj5)
	(connected obj9 obj11)
	(connected obj10 obj3)
	(connected obj11 obj5)
	(connected obj11 obj9)
	(connected obj11 obj12)
	(connected obj12 obj11)
	(connected obj13 obj1)
	(connected obj13 obj2)
	(connected obj14 obj5)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj13)
))
)