(define (problem problem_835)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj5)
	(connected obj1 obj6)
	(connected obj1 obj7)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj6)
	(connected obj2 obj8)
	(connected obj3 obj0)
	(connected obj3 obj2)
	(connected obj3 obj5)
	(connected obj3 obj11)
	(connected obj3 obj12)
	(connected obj4 obj0)
	(connected obj4 obj2)
	(connected obj4 obj9)
	(connected obj4 obj12)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj3)
	(connected obj5 obj10)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj2)
	(connected obj6 obj7)
	(connected obj6 obj9)
	(connected obj7 obj1)
	(connected obj7 obj6)
	(connected obj7 obj8)
	(connected obj8 obj0)
	(connected obj8 obj2)
	(connected obj8 obj7)
	(connected obj8 obj13)
	(connected obj9 obj6)
	(connected obj9 obj13)
	(connected obj10 obj5)
	(connected obj11 obj3)
	(connected obj12 obj3)
	(connected obj12 obj7)
	(connected obj13 obj8)
	(connected obj13 obj9)
	(connected obj13 obj14)
	(connected obj14 obj13)
)

(:goal (and
	(visited obj0)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj12)
))
)