(define (problem problem_1280)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj6)
	(connected obj0 obj8)
	(connected obj0 obj9)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj5)
	(connected obj1 obj8)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj3 obj0)
	(connected obj3 obj4)
	(connected obj3 obj8)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj4 obj13)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj4)
	(connected obj5 obj8)
	(connected obj5 obj11)
	(connected obj6 obj0)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj6 obj9)
	(connected obj6 obj12)
	(connected obj7 obj1)
	(connected obj7 obj2)
	(connected obj7 obj6)
	(connected obj8 obj3)
	(connected obj8 obj5)
	(connected obj9 obj0)
	(connected obj9 obj11)
	(connected obj10 obj11)
	(connected obj11 obj5)
	(connected obj11 obj9)
	(connected obj11 obj10)
	(connected obj12 obj6)
	(connected obj12 obj8)
	(connected obj13 obj4)
	(connected obj14 obj12)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
))
)