(define (problem problem_1767)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj9)
	(connected obj0 obj10)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj5)
	(connected obj1 obj7)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj13)
	(connected obj3 obj2)
	(connected obj3 obj7)
	(connected obj4 obj2)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj4)
	(connected obj5 obj7)
	(connected obj5 obj8)
	(connected obj5 obj10)
	(connected obj6 obj0)
	(connected obj6 obj4)
	(connected obj6 obj11)
	(connected obj7 obj0)
	(connected obj7 obj2)
	(connected obj7 obj3)
	(connected obj7 obj5)
	(connected obj7 obj12)
	(connected obj8 obj5)
	(connected obj8 obj9)
	(connected obj9 obj0)
	(connected obj9 obj8)
	(connected obj9 obj12)
	(connected obj9 obj13)
	(connected obj10 obj0)
	(connected obj10 obj5)
	(connected obj11 obj6)
	(connected obj12 obj7)
	(connected obj12 obj9)
	(connected obj13 obj2)
	(connected obj14 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj9)
	(visited obj12)
	(visited obj13)
))
)