(define (problem problem_316)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj0 obj9)
	(connected obj0 obj12)
	(connected obj0 obj14)
	(connected obj1 obj0)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj13)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj9)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj7)
	(connected obj4 obj8)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj9)
	(connected obj5 obj10)
	(connected obj5 obj11)
	(connected obj6 obj1)
	(connected obj6 obj9)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj7 obj8)
	(connected obj8 obj4)
	(connected obj8 obj7)
	(connected obj8 obj10)
	(connected obj8 obj11)
	(connected obj9 obj0)
	(connected obj9 obj3)
	(connected obj9 obj5)
	(connected obj9 obj6)
	(connected obj10 obj5)
	(connected obj10 obj8)
	(connected obj11 obj5)
	(connected obj11 obj8)
	(connected obj12 obj0)
	(connected obj13 obj2)
	(connected obj14 obj0)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)