(define (problem problem_803)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj10)
	(connected obj0 obj11)
	(connected obj1 obj0)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj1 obj7)
	(connected obj1 obj10)
	(connected obj1 obj12)
	(connected obj2 obj0)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj3 obj0)
	(connected obj3 obj8)
	(connected obj4 obj1)
	(connected obj4 obj6)
	(connected obj4 obj9)
	(connected obj4 obj11)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj7)
	(connected obj6 obj0)
	(connected obj6 obj2)
	(connected obj6 obj4)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj8)
	(connected obj7 obj10)
	(connected obj8 obj3)
	(connected obj8 obj7)
	(connected obj8 obj9)
	(connected obj9 obj4)
	(connected obj9 obj8)
	(connected obj9 obj13)
	(connected obj10 obj0)
	(connected obj10 obj1)
	(connected obj10 obj7)
	(connected obj11 obj0)
	(connected obj11 obj4)
	(connected obj12 obj6)
	(connected obj12 obj13)
	(connected obj13 obj2)
	(connected obj13 obj9)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj13)
))
)