(define (problem problem_392)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj8)
	(connected obj0 obj14)
	(connected obj1 obj0)
	(connected obj2 obj0)
	(connected obj2 obj4)
	(connected obj2 obj9)
	(connected obj3 obj0)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj7)
	(connected obj4 obj0)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj10)
	(connected obj4 obj13)
	(connected obj5 obj0)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj5 obj7)
	(connected obj6 obj1)
	(connected obj6 obj5)
	(connected obj6 obj8)
	(connected obj6 obj9)
	(connected obj7 obj5)
	(connected obj7 obj9)
	(connected obj8 obj0)
	(connected obj8 obj6)
	(connected obj8 obj9)
	(connected obj8 obj14)
	(connected obj9 obj2)
	(connected obj9 obj6)
	(connected obj9 obj7)
	(connected obj9 obj8)
	(connected obj9 obj13)
	(connected obj10 obj4)
	(connected obj10 obj9)
	(connected obj11 obj3)
	(connected obj11 obj9)
	(connected obj12 obj3)
	(connected obj12 obj11)
	(connected obj13 obj4)
	(connected obj13 obj9)
	(connected obj14 obj0)
	(connected obj14 obj8)
)

(:goal (and
	(visited obj0)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
	(visited obj14)
))
)