(define (problem problem_935)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj6)
	(connected obj0 obj8)
	(connected obj0 obj9)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj8)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj11)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj4 obj0)
	(connected obj4 obj5)
	(connected obj4 obj9)
	(connected obj4 obj11)
	(connected obj5 obj2)
	(connected obj5 obj4)
	(connected obj5 obj6)
	(connected obj5 obj9)
	(connected obj6 obj0)
	(connected obj6 obj5)
	(connected obj6 obj7)
	(connected obj6 obj10)
	(connected obj7 obj2)
	(connected obj7 obj6)
	(connected obj7 obj9)
	(connected obj7 obj12)
	(connected obj8 obj0)
	(connected obj8 obj1)
	(connected obj9 obj0)
	(connected obj9 obj4)
	(connected obj9 obj5)
	(connected obj9 obj7)
	(connected obj10 obj6)
	(connected obj10 obj11)
	(connected obj11 obj2)
	(connected obj11 obj4)
	(connected obj11 obj10)
	(connected obj11 obj12)
	(connected obj12 obj7)
	(connected obj12 obj11)
	(connected obj13 obj8)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj11)
	(visited obj12)
))
)