(define (problem problem_1469)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj6)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj9)
	(connected obj2 obj10)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj6)
	(connected obj3 obj7)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj6)
	(connected obj4 obj7)
	(connected obj4 obj9)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj5 obj8)
	(connected obj5 obj9)
	(connected obj5 obj10)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj3)
	(connected obj6 obj4)
	(connected obj6 obj5)
	(connected obj6 obj7)
	(connected obj7 obj3)
	(connected obj7 obj4)
	(connected obj7 obj6)
	(connected obj7 obj8)
	(connected obj7 obj9)
	(connected obj8 obj5)
	(connected obj8 obj7)
	(connected obj9 obj2)
	(connected obj9 obj4)
	(connected obj9 obj7)
	(connected obj10 obj2)
	(connected obj10 obj5)
	(connected obj11 obj6)
	(connected obj12 obj1)
	(connected obj13 obj14)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj9)
	(visited obj10)
))
)