(define (problem problem_555)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj12)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj3 obj0)
	(connected obj4 obj2)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj4 obj9)
	(connected obj5 obj4)
	(connected obj5 obj11)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj6 obj9)
	(connected obj7 obj1)
	(connected obj7 obj6)
	(connected obj7 obj10)
	(connected obj8 obj2)
	(connected obj9 obj4)
	(connected obj9 obj6)
	(connected obj10 obj4)
	(connected obj10 obj7)
	(connected obj12 obj0)
)

(:goal (and
	(visited obj4)
	(visited obj5)
	(visited obj11)
))
)