(define (problem problem_246)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj5)
	(connected obj1 obj7)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj2 obj9)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj9)
	(connected obj3 obj10)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj7)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj10)
	(connected obj6 obj0)
	(connected obj6 obj2)
	(connected obj6 obj8)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj7 obj8)
	(connected obj8 obj6)
	(connected obj8 obj7)
	(connected obj8 obj12)
	(connected obj9 obj2)
	(connected obj9 obj12)
	(connected obj10 obj3)
	(connected obj10 obj5)
	(connected obj10 obj11)
	(connected obj10 obj12)
	(connected obj11 obj1)
	(connected obj11 obj10)
	(connected obj12 obj8)
	(connected obj12 obj9)
	(connected obj13 obj5)
	(connected obj14 obj8)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj12)
))
)