(define (problem problem_605)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj8)
	(connected obj0 obj10)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj4)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj7)
	(connected obj2 obj8)
	(connected obj2 obj12)
	(connected obj3 obj0)
	(connected obj3 obj2)
	(connected obj3 obj5)
	(connected obj3 obj8)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj6)
	(connected obj4 obj7)
	(connected obj4 obj9)
	(connected obj4 obj12)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj5 obj10)
	(connected obj6 obj4)
	(connected obj6 obj5)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj7 obj11)
	(connected obj8 obj0)
	(connected obj8 obj2)
	(connected obj8 obj3)
	(connected obj8 obj9)
	(connected obj8 obj10)
	(connected obj8 obj12)
	(connected obj9 obj8)
	(connected obj9 obj10)
	(connected obj10 obj5)
	(connected obj10 obj8)
	(connected obj10 obj9)
	(connected obj10 obj12)
	(connected obj11 obj7)
	(connected obj12 obj2)
	(connected obj12 obj8)
	(connected obj12 obj10)
)

(:goal (and
	(visited obj0)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj10)
	(visited obj12)
))
)