(define (problem problem_1819)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj8)
	(connected obj0 obj9)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj1 obj6)
	(connected obj1 obj8)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj6)
	(connected obj3 obj9)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj7)
	(connected obj4 obj10)
	(connected obj4 obj11)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj10)
	(connected obj5 obj12)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj3)
	(connected obj7 obj0)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj7 obj9)
	(connected obj8 obj0)
	(connected obj8 obj1)
	(connected obj8 obj10)
	(connected obj9 obj0)
	(connected obj9 obj3)
	(connected obj9 obj7)
	(connected obj10 obj4)
	(connected obj10 obj5)
	(connected obj10 obj8)
	(connected obj11 obj4)
	(connected obj12 obj5)
	(connected obj12 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)