(define (problem problem_491)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj4)
	(connected obj0 obj1)
	(connected obj0 obj4)
	(connected obj1 obj0)
	(connected obj1 obj4)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj3 obj4)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj4 obj7)
	(connected obj4 obj8)
	(connected obj4 obj9)
	(connected obj4 obj10)
	(connected obj4 obj11)
	(connected obj4 obj12)
	(connected obj4 obj13)
	(connected obj4 obj14)
	(connected obj5 obj4)
	(connected obj5 obj6)
	(connected obj6 obj0)
	(connected obj6 obj4)
	(connected obj7 obj4)
	(connected obj8 obj4)
	(connected obj8 obj10)
	(connected obj9 obj4)
	(connected obj9 obj7)
	(connected obj10 obj4)
	(connected obj11 obj4)
	(connected obj12 obj4)
	(connected obj13 obj4)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
	(visited obj13)
))
)