(define (problem problem_459)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj5)
	(connected obj0 obj7)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj6)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj8)
	(connected obj3 obj2)
	(connected obj3 obj4)
	(connected obj3 obj6)
	(connected obj3 obj7)
	(connected obj4 obj2)
	(connected obj4 obj5)
	(connected obj5 obj0)
	(connected obj6 obj1)
	(connected obj7 obj1)
	(connected obj7 obj2)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj8)
))
)