(define (problem problem_103)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj8)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj5)
	(connected obj4 obj0)
	(connected obj4 obj2)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj4)
	(connected obj6 obj2)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj7 obj6)
	(connected obj8 obj1)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj4)
))
)