(define (problem problem_377)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj1 obj10)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj5)
	(connected obj2 obj8)
	(connected obj3 obj4)
	(connected obj4 obj1)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj4 obj7)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj3)
	(connected obj6 obj7)
	(connected obj7 obj1)
	(connected obj7 obj4)
	(connected obj7 obj5)
	(connected obj9 obj3)
	(connected obj10 obj8)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj8)
	(visited obj10)
))
)