(define (problem problem_256)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj5)
	(connected obj3 obj2)
	(connected obj3 obj6)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj9)
	(connected obj5 obj0)
	(connected obj5 obj4)
	(connected obj5 obj6)
	(connected obj5 obj11)
	(connected obj5 obj12)
	(connected obj6 obj2)
	(connected obj6 obj5)
	(connected obj6 obj7)
	(connected obj8 obj9)
	(connected obj9 obj2)
	(connected obj9 obj3)
	(connected obj9 obj4)
	(connected obj9 obj8)
	(connected obj10 obj5)
	(connected obj11 obj3)
	(connected obj12 obj4)
	(connected obj13 obj2)
	(connected obj13 obj4)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj8)
	(visited obj9)
	(visited obj11)
))
)