(define (problem problem_498)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj8)
	(connected obj0 obj9)
	(connected obj1 obj3)
	(connected obj1 obj6)
	(connected obj1 obj7)
	(connected obj2 obj0)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj4 obj2)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj5 obj3)
	(connected obj5 obj4)
	(connected obj6 obj2)
	(connected obj6 obj3)
	(connected obj6 obj7)
	(connected obj6 obj9)
	(connected obj6 obj10)
	(connected obj7 obj5)
	(connected obj7 obj6)
	(connected obj8 obj0)
	(connected obj9 obj8)
	(connected obj9 obj10)
	(connected obj10 obj7)
	(connected obj11 obj3)
	(connected obj12 obj2)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj9)
	(visited obj10)
))
)