(define (problem problem_59)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 - place
)

(:init
	(at_robot obj4)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj10)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj9)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj3)
	(connected obj4 obj7)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj6 obj3)
	(connected obj6 obj8)
	(connected obj7 obj0)
	(connected obj8 obj6)
	(connected obj9 obj3)
	(connected obj10 obj3)
	(connected obj10 obj7)
	(connected obj11 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj8)
	(visited obj10)
))
)