(define (problem problem_129)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj7)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj1 obj10)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj6)
	(connected obj3 obj0)
	(connected obj3 obj7)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj8)
	(connected obj5 obj1)
	(connected obj6 obj3)
	(connected obj6 obj5)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj3)
	(connected obj8 obj3)
	(connected obj8 obj10)
	(connected obj9 obj6)
	(connected obj10 obj1)
	(connected obj10 obj11)
	(connected obj11 obj1)
	(connected obj12 obj3)
	(connected obj12 obj8)
	(connected obj12 obj11)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj10)
	(visited obj11)
))
)