(define (problem problem_305)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj1 obj0)
	(connected obj1 obj4)
	(connected obj1 obj9)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj5)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj6)
	(connected obj4 obj1)
	(connected obj4 obj3)
	(connected obj4 obj6)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj8)
	(connected obj5 obj11)
	(connected obj6 obj7)
	(connected obj7 obj8)
	(connected obj9 obj2)
	(connected obj10 obj3)
	(connected obj10 obj4)
	(connected obj10 obj12)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj3)
	(visited obj4)
	(visited obj6)
	(visited obj7)
	(visited obj8)
))
)