(define (problem problem_308)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj6)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj1 obj8)
	(connected obj1 obj11)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj3 obj4)
	(connected obj3 obj6)
	(connected obj4 obj2)
	(connected obj5 obj4)
	(connected obj5 obj11)
	(connected obj6 obj7)
	(connected obj6 obj13)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj4)
	(connected obj7 obj9)
	(connected obj8 obj0)
	(connected obj8 obj1)
	(connected obj8 obj7)
	(connected obj8 obj10)
	(connected obj9 obj4)
	(connected obj10 obj4)
	(connected obj11 obj4)
	(connected obj12 obj1)
	(connected obj13 obj1)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj6)
	(visited obj8)
	(visited obj10)
))
)