(define (problem problem_94)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj6)
	(connected obj3 obj1)
	(connected obj3 obj9)
	(connected obj4 obj1)
	(connected obj4 obj7)
	(connected obj5 obj6)
	(connected obj5 obj7)
	(connected obj5 obj12)
	(connected obj6 obj2)
	(connected obj6 obj8)
	(connected obj6 obj10)
	(connected obj7 obj4)
	(connected obj7 obj6)
	(connected obj7 obj12)
	(connected obj8 obj0)
	(connected obj8 obj5)
	(connected obj8 obj6)
	(connected obj8 obj13)
	(connected obj9 obj2)
	(connected obj9 obj7)
	(connected obj9 obj10)
	(connected obj11 obj6)
	(connected obj11 obj9)
	(connected obj12 obj2)
)

(:goal (and
	(visited obj6)
	(visited obj8)
	(visited obj13)
))
)