(define (problem problem_333)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj6)
	(connected obj1 obj7)
	(connected obj2 obj0)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj4 obj3)
	(connected obj5 obj3)
	(connected obj5 obj6)
	(connected obj5 obj10)
	(connected obj5 obj11)
	(connected obj6 obj0)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj6)
	(connected obj8 obj4)
	(connected obj8 obj9)
	(connected obj10 obj6)
	(connected obj10 obj9)
	(connected obj12 obj8)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj6)
	(visited obj7)
))
)