(define (problem problem_15)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj10)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj12)
	(connected obj3 obj0)
	(connected obj3 obj5)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj13)
	(connected obj5 obj4)
	(connected obj5 obj8)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj7 obj5)
	(connected obj7 obj8)
	(connected obj7 obj11)
	(connected obj7 obj13)
	(connected obj8 obj0)
	(connected obj8 obj1)
	(connected obj8 obj5)
	(connected obj8 obj9)
	(connected obj9 obj4)
	(connected obj9 obj11)
	(connected obj10 obj0)
	(connected obj10 obj1)
	(connected obj10 obj2)
	(connected obj12 obj1)
	(connected obj12 obj5)
	(connected obj13 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj13)
))
)