(define (problem problem_100)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj2 obj1)
	(connected obj2 obj5)
	(connected obj2 obj9)
	(connected obj2 obj11)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj9)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj4 obj12)
	(connected obj5 obj0)
	(connected obj5 obj4)
	(connected obj5 obj8)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj6 obj8)
	(connected obj7 obj5)
	(connected obj8 obj3)
	(connected obj8 obj5)
	(connected obj8 obj10)
	(connected obj9 obj0)
	(connected obj9 obj2)
	(connected obj10 obj0)
	(connected obj11 obj2)
	(connected obj11 obj5)
	(connected obj11 obj9)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj8)
	(visited obj12)
))
)