(define (problem problem_61)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj4)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj6)
	(connected obj4 obj2)
	(connected obj4 obj7)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj4)
	(connected obj5 obj7)
	(connected obj6 obj2)
	(connected obj7 obj1)
	(connected obj7 obj5)
	(connected obj8 obj7)
	(connected obj8 obj9)
	(connected obj9 obj5)
	(connected obj10 obj5)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj7)
))
)