(define (problem problem_108)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj0 obj7)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj4)
	(connected obj1 obj7)
	(connected obj1 obj9)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj9)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj6 obj3)
	(connected obj6 obj4)
	(connected obj6 obj5)
	(connected obj6 obj7)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj2)
	(connected obj7 obj6)
	(connected obj7 obj8)
	(connected obj8 obj0)
	(connected obj9 obj1)
	(connected obj9 obj4)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj8)
	(visited obj9)
))
)