(define (problem problem_190)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj7)
	(connected obj2 obj3)
	(connected obj3 obj0)
	(connected obj3 obj4)
	(connected obj3 obj7)
	(connected obj3 obj10)
	(connected obj3 obj11)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj6)
	(connected obj6 obj0)
	(connected obj6 obj9)
	(connected obj7 obj0)
	(connected obj7 obj2)
	(connected obj7 obj5)
	(connected obj7 obj8)
	(connected obj7 obj12)
	(connected obj8 obj0)
	(connected obj8 obj7)
	(connected obj9 obj1)
	(connected obj9 obj2)
	(connected obj10 obj8)
	(connected obj11 obj7)
	(connected obj11 obj8)
	(connected obj12 obj1)
	(connected obj12 obj3)
	(connected obj12 obj4)
	(connected obj12 obj8)
	(connected obj12 obj9)
)

(:goal (and
	(visited obj0)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj11)
))
)