(define (problem problem_425)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj7)
	(connected obj1 obj10)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj6)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj5)
	(connected obj3 obj10)
	(connected obj4 obj0)
	(connected obj4 obj9)
	(connected obj4 obj13)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj7)
	(connected obj6 obj0)
	(connected obj6 obj8)
	(connected obj7 obj3)
	(connected obj7 obj8)
	(connected obj8 obj0)
	(connected obj8 obj3)
	(connected obj8 obj6)
	(connected obj9 obj2)
	(connected obj9 obj3)
	(connected obj10 obj8)
	(connected obj11 obj8)
	(connected obj12 obj5)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj3)
	(visited obj5)
	(visited obj6)
	(visited obj8)
	(visited obj10)
))
)