(define (problem problem_109)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj10)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj7)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj6)
	(connected obj3 obj9)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj7)
	(connected obj5 obj0)
	(connected obj5 obj3)
	(connected obj6 obj3)
	(connected obj6 obj8)
	(connected obj7 obj1)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj8 obj6)
	(connected obj9 obj3)
	(connected obj10 obj1)
	(connected obj10 obj4)
	(connected obj10 obj11)
	(connected obj11 obj10)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj10)
	(visited obj11)
))
)