(define (problem problem_426)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj6)
	(connected obj1 obj7)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj2 obj8)
	(connected obj2 obj10)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj7)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj4 obj7)
	(connected obj4 obj9)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj4)
	(connected obj5 obj6)
	(connected obj6 obj1)
	(connected obj6 obj2)
	(connected obj6 obj5)
	(connected obj7 obj1)
	(connected obj7 obj3)
	(connected obj7 obj4)
	(connected obj8 obj2)
	(connected obj9 obj4)
	(connected obj10 obj2)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)