(define (problem problem_307)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj10)
	(connected obj1 obj0)
	(connected obj1 obj11)
	(connected obj2 obj3)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj2 obj9)
	(connected obj3 obj0)
	(connected obj3 obj2)
	(connected obj3 obj4)
	(connected obj3 obj7)
	(connected obj3 obj10)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj6)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj6 obj0)
	(connected obj6 obj2)
	(connected obj6 obj4)
	(connected obj7 obj3)
	(connected obj7 obj8)
	(connected obj8 obj7)
	(connected obj9 obj2)
	(connected obj10 obj0)
	(connected obj10 obj3)
	(connected obj11 obj1)
	(connected obj12 obj10)
	(connected obj13 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj9)
	(visited obj11)
))
)