(define (problem problem_34)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj6)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj5)
	(connected obj3 obj11)
	(connected obj4 obj1)
	(connected obj4 obj7)
	(connected obj4 obj12)
	(connected obj5 obj3)
	(connected obj5 obj8)
	(connected obj6 obj0)
	(connected obj6 obj8)
	(connected obj7 obj4)
	(connected obj7 obj11)
	(connected obj8 obj5)
	(connected obj8 obj6)
	(connected obj8 obj9)
	(connected obj9 obj8)
	(connected obj9 obj10)
	(connected obj10 obj9)
	(connected obj11 obj3)
	(connected obj11 obj7)
	(connected obj12 obj4)
	(connected obj12 obj13)
	(connected obj13 obj12)
)

(:goal (and
	(visited obj0)
	(visited obj2)
	(visited obj3)
	(visited obj5)
	(visited obj6)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)