(define (problem problem_59)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj4)
	(connected obj0 obj6)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj7)
	(connected obj2 obj11)
	(connected obj3 obj4)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj6 obj0)
	(connected obj7 obj2)
	(connected obj8 obj5)
	(connected obj9 obj10)
	(connected obj9 obj11)
	(connected obj10 obj9)
	(connected obj11 obj2)
	(connected obj11 obj6)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj6)
))
)