(define (problem problem_18)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj4)
	(connected obj0 obj7)
	(connected obj0 obj8)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj2 obj0)
	(connected obj2 obj8)
	(connected obj2 obj9)
	(connected obj3 obj1)
	(connected obj3 obj5)
	(connected obj3 obj6)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj6)
	(connected obj4 obj7)
	(connected obj5 obj3)
	(connected obj6 obj3)
	(connected obj6 obj4)
	(connected obj6 obj9)
	(connected obj7 obj4)
	(connected obj7 obj6)
	(connected obj7 obj9)
	(connected obj8 obj0)
	(connected obj8 obj2)
	(connected obj9 obj4)
	(connected obj9 obj7)
	(connected obj9 obj10)
	(connected obj10 obj3)
	(connected obj10 obj9)
	(connected obj11 obj9)
	(connected obj12 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)