(define (problem problem_27)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj1)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj4)
	(connected obj1 obj5)
	(connected obj1 obj9)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj3 obj2)
	(connected obj3 obj4)
	(connected obj4 obj1)
	(connected obj4 obj3)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj2)
	(connected obj5 obj6)
	(connected obj6 obj2)
	(connected obj6 obj5)
	(connected obj6 obj12)
	(connected obj7 obj8)
	(connected obj8 obj7)
	(connected obj8 obj9)
	(connected obj8 obj10)
	(connected obj9 obj1)
	(connected obj9 obj8)
	(connected obj10 obj6)
	(connected obj10 obj8)
	(connected obj11 obj5)
	(connected obj13 obj10)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj12)
))
)