(define (problem problem_276)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj9)
	(connected obj0 obj12)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj4)
	(connected obj1 obj7)
	(connected obj1 obj8)
	(connected obj1 obj9)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj5)
	(connected obj3 obj0)
	(connected obj3 obj2)
	(connected obj3 obj5)
	(connected obj3 obj7)
	(connected obj4 obj1)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj5 obj2)
	(connected obj5 obj4)
	(connected obj5 obj7)
	(connected obj5 obj9)
	(connected obj6 obj4)
	(connected obj6 obj9)
	(connected obj7 obj1)
	(connected obj7 obj3)
	(connected obj7 obj5)
	(connected obj7 obj8)
	(connected obj7 obj11)
	(connected obj8 obj1)
	(connected obj8 obj2)
	(connected obj8 obj5)
	(connected obj8 obj7)
	(connected obj9 obj0)
	(connected obj9 obj1)
	(connected obj9 obj5)
	(connected obj9 obj6)
	(connected obj9 obj7)
	(connected obj10 obj7)
	(connected obj10 obj11)
	(connected obj11 obj7)
	(connected obj11 obj10)
	(connected obj12 obj0)
	(connected obj12 obj1)
	(connected obj12 obj13)
	(connected obj13 obj12)
	(connected obj14 obj8)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj5)
	(visited obj7)
	(visited obj8)
	(visited obj9)
	(visited obj12)
	(visited obj13)
))
)