(define (problem problem_477)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj8)
	(connected obj0 obj11)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj5)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj8)
	(connected obj2 obj9)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj3 obj7)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj4 obj8)
	(connected obj5 obj0)
	(connected obj5 obj1)
	(connected obj5 obj4)
	(connected obj5 obj7)
	(connected obj5 obj12)
	(connected obj6 obj0)
	(connected obj6 obj1)
	(connected obj6 obj8)
	(connected obj6 obj9)
	(connected obj7 obj3)
	(connected obj7 obj5)
	(connected obj8 obj2)
	(connected obj8 obj4)
	(connected obj8 obj6)
	(connected obj8 obj10)
	(connected obj9 obj2)
	(connected obj9 obj6)
	(connected obj9 obj10)
	(connected obj10 obj9)
	(connected obj11 obj0)
	(connected obj12 obj5)
	(connected obj13 obj8)
)

(:goal (and
	(visited obj0)
	(visited obj2)
	(visited obj6)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)