(define (problem problem_1277)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj9)
	(connected obj0 obj10)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj2 obj0)
	(connected obj2 obj3)
	(connected obj2 obj8)
	(connected obj2 obj9)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj7)
	(connected obj3 obj8)
	(connected obj4 obj5)
	(connected obj4 obj8)
	(connected obj4 obj10)
	(connected obj4 obj11)
	(connected obj5 obj4)
	(connected obj5 obj6)
	(connected obj5 obj7)
	(connected obj5 obj8)
	(connected obj5 obj9)
	(connected obj6 obj0)
	(connected obj6 obj5)
	(connected obj6 obj7)
	(connected obj6 obj8)
	(connected obj7 obj0)
	(connected obj7 obj3)
	(connected obj7 obj4)
	(connected obj7 obj11)
	(connected obj8 obj2)
	(connected obj8 obj3)
	(connected obj8 obj4)
	(connected obj8 obj5)
	(connected obj8 obj6)
	(connected obj8 obj9)
	(connected obj9 obj0)
	(connected obj9 obj2)
	(connected obj9 obj5)
	(connected obj9 obj8)
	(connected obj10 obj0)
	(connected obj10 obj4)
	(connected obj11 obj4)
	(connected obj11 obj5)
	(connected obj11 obj7)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj7)
	(visited obj8)
	(visited obj9)
))
)