(define (problem problem_85)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj6)
	(connected obj0 obj8)
	(connected obj0 obj10)
	(connected obj0 obj11)
	(connected obj0 obj12)
	(connected obj1 obj0)
	(connected obj1 obj7)
	(connected obj1 obj9)
	(connected obj2 obj0)
	(connected obj2 obj7)
	(connected obj2 obj8)
	(connected obj3 obj0)
	(connected obj3 obj10)
	(connected obj4 obj0)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj4 obj7)
	(connected obj4 obj10)
	(connected obj5 obj0)
	(connected obj5 obj4)
	(connected obj5 obj7)
	(connected obj5 obj8)
	(connected obj5 obj9)
	(connected obj5 obj10)
	(connected obj6 obj0)
	(connected obj6 obj4)
	(connected obj6 obj9)
	(connected obj7 obj1)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj7 obj5)
	(connected obj8 obj0)
	(connected obj8 obj2)
	(connected obj8 obj5)
	(connected obj9 obj5)
	(connected obj9 obj6)
	(connected obj10 obj0)
	(connected obj10 obj4)
	(connected obj10 obj5)
	(connected obj10 obj11)
	(connected obj11 obj0)
	(connected obj11 obj10)
	(connected obj12 obj0)
	(connected obj12 obj2)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj4)
	(visited obj5)
	(visited obj7)
	(visited obj8)
))
)