(define (problem problem_1807)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj9)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj4)
	(connected obj1 obj7)
	(connected obj1 obj10)
	(connected obj2 obj0)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj9)
	(connected obj2 obj11)
	(connected obj3 obj1)
	(connected obj3 obj5)
	(connected obj3 obj7)
	(connected obj3 obj9)
	(connected obj3 obj11)
	(connected obj4 obj0)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj4 obj8)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj4)
	(connected obj5 obj10)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj7 obj1)
	(connected obj7 obj3)
	(connected obj7 obj6)
	(connected obj8 obj3)
	(connected obj8 obj4)
	(connected obj8 obj10)
	(connected obj9 obj1)
	(connected obj9 obj2)
	(connected obj9 obj10)
	(connected obj10 obj1)
	(connected obj10 obj5)
	(connected obj10 obj8)
	(connected obj10 obj9)
	(connected obj10 obj11)
	(connected obj11 obj2)
	(connected obj11 obj3)
	(connected obj11 obj10)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)