(define (problem problem_1877)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj5)
	(connected obj0 obj7)
	(connected obj0 obj11)
	(connected obj1 obj0)
	(connected obj1 obj3)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj3)
	(connected obj2 obj8)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj4)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj5 obj0)
	(connected obj5 obj4)
	(connected obj5 obj6)
	(connected obj6 obj1)
	(connected obj6 obj5)
	(connected obj7 obj0)
	(connected obj8 obj2)
	(connected obj8 obj9)
	(connected obj9 obj8)
	(connected obj9 obj10)
	(connected obj10 obj9)
	(connected obj11 obj0)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)