(define (problem problem_711)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj9)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj1 obj5)
	(connected obj1 obj6)
	(connected obj1 obj7)
	(connected obj1 obj9)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj4)
	(connected obj3 obj5)
	(connected obj3 obj8)
	(connected obj3 obj10)
	(connected obj4 obj0)
	(connected obj4 obj2)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj5 obj1)
	(connected obj5 obj3)
	(connected obj5 obj4)
	(connected obj5 obj8)
	(connected obj5 obj12)
	(connected obj6 obj1)
	(connected obj6 obj9)
	(connected obj6 obj11)
	(connected obj6 obj13)
	(connected obj6 obj14)
	(connected obj7 obj1)
	(connected obj7 obj11)
	(connected obj8 obj3)
	(connected obj8 obj9)
	(connected obj9 obj0)
	(connected obj9 obj6)
	(connected obj9 obj8)
	(connected obj10 obj3)
	(connected obj11 obj6)
	(connected obj11 obj7)
	(connected obj12 obj5)
	(connected obj13 obj1)
	(connected obj13 obj6)
	(connected obj14 obj6)
)

(:goal (and
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj6)
	(visited obj7)
	(visited obj9)
	(visited obj11)
	(visited obj13)
))
)