(define (problem problem_494)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 obj15 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj9)
	(connected obj0 obj10)
	(connected obj0 obj13)
	(connected obj0 obj14)
	(connected obj0 obj15)
	(connected obj1 obj0)
	(connected obj1 obj4)
	(connected obj2 obj0)
	(connected obj2 obj3)
	(connected obj2 obj6)
	(connected obj3 obj2)
	(connected obj3 obj8)
	(connected obj4 obj1)
	(connected obj4 obj6)
	(connected obj5 obj4)
	(connected obj5 obj9)
	(connected obj6 obj0)
	(connected obj6 obj2)
	(connected obj6 obj4)
	(connected obj6 obj7)
	(connected obj7 obj0)
	(connected obj7 obj6)
	(connected obj7 obj8)
	(connected obj7 obj11)
	(connected obj8 obj5)
	(connected obj8 obj7)
	(connected obj9 obj0)
	(connected obj9 obj4)
	(connected obj12 obj5)
	(connected obj15 obj3)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj4)
	(visited obj6)
	(visited obj10)
))
)