(define (problem problem_458)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj5)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj6)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj2 obj12)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj2)
	(connected obj3 obj5)
	(connected obj4 obj1)
	(connected obj4 obj2)
	(connected obj4 obj8)
	(connected obj5 obj0)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj5 obj9)
	(connected obj7 obj0)
	(connected obj7 obj1)
	(connected obj7 obj8)
	(connected obj8 obj4)
	(connected obj8 obj10)
	(connected obj9 obj0)
	(connected obj9 obj5)
	(connected obj10 obj2)
	(connected obj11 obj6)
	(connected obj11 obj9)
)

(:goal (and
	(visited obj0)
	(visited obj1)
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj8)
	(visited obj9)
	(visited obj10)
))
)