(define (problem problem_244)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 - place
)

(:init
	(at_robot obj0)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj0 obj6)
	(connected obj0 obj7)
	(connected obj0 obj8)
	(connected obj0 obj9)
	(connected obj0 obj10)
	(connected obj0 obj12)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj3 obj0)
	(connected obj3 obj1)
	(connected obj3 obj4)
	(connected obj4 obj0)
	(connected obj4 obj3)
	(connected obj4 obj5)
	(connected obj5 obj4)
	(connected obj5 obj7)
	(connected obj6 obj0)
	(connected obj6 obj2)
	(connected obj6 obj4)
	(connected obj6 obj9)
	(connected obj7 obj11)
	(connected obj8 obj0)
	(connected obj8 obj3)
	(connected obj9 obj0)
	(connected obj9 obj5)
	(connected obj10 obj0)
	(connected obj10 obj4)
	(connected obj11 obj7)
	(connected obj13 obj6)
)

(:goal (and
	(visited obj12)
))
)