(define (problem problem_402)

(:domain visitall)

(:objects
	obj0 obj1 obj2 obj3 obj4 obj5 obj6 obj7 obj8 obj9 obj10 obj11 obj12 obj13 obj14 - place
)

(:init
	(at_robot obj2)
	(connected obj0 obj1)
	(connected obj0 obj2)
	(connected obj0 obj3)
	(connected obj0 obj4)
	(connected obj1 obj0)
	(connected obj1 obj2)
	(connected obj1 obj3)
	(connected obj2 obj0)
	(connected obj2 obj1)
	(connected obj2 obj3)
	(connected obj2 obj4)
	(connected obj2 obj5)
	(connected obj2 obj6)
	(connected obj2 obj8)
	(connected obj2 obj9)
	(connected obj3 obj5)
	(connected obj4 obj5)
	(connected obj4 obj6)
	(connected obj5 obj2)
	(connected obj5 obj3)
	(connected obj6 obj2)
	(connected obj6 obj8)
	(connected obj7 obj2)
	(connected obj7 obj4)
	(connected obj8 obj2)
	(connected obj8 obj5)
	(connected obj8 obj10)
	(connected obj9 obj2)
	(connected obj9 obj5)
	(connected obj10 obj0)
	(connected obj11 obj7)
	(connected obj12 obj1)
	(connected obj13 obj6)
	(connected obj14 obj5)
)

(:goal (and
	(visited obj2)
	(visited obj3)
	(visited obj4)
	(visited obj5)
	(visited obj6)
	(visited obj8)
	(visited obj9)
))
)